name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build and Push Images
      run: |
        docker build -t ${{ secrets.DOCKER_USER }}/backend:latest ./backend/service1
        docker push ${{ secrets.DOCKER_USER }}/backend:latest

        docker build -t ${{ secrets.DOCKER_USER }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USER }}/frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user

          if [ ! -d devops-project ]; then
            git clone https://github.com/sourabh1985/devops-k8s-project
          fi

          cd devops-project
          git pull

          kubectl apply -f k8s/